### ISSUE TITLE
Bug for create table

### ISSUE THREAD

**Issue by CYouth** [callMeName/MiniSql#4]
I have found a series bug,when the length of the name of table is great than or equal to 8, it can't create the index for primary key
![image](https://user-images.githubusercontent.com/17637240/59563040-44b11d00-9067-11e9-80d3-793ac79fabc7.png)
Could you please explain why？because this bug has been bothering me for a while

**Comment by callMeName** [comment]
Hey @CYouth, thanks for pointing it out! Sorry this repository is more a demo than a maintained project.
Also it's really been a while this is touched. I do not recall any existing issues.
